### ISSUE TITLE
load database error

### ISSUE THREAD

**Issue by ktpss95112** [amjltc295/SQL_Homework#13]
I had encountered "ERROR 1698 (28000): Access denied for user 'b07902123'@'localhost'", so I had done [something](https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost) and this is my user table:
![image](https://user-images.githubusercontent.com/20783464/50385053-627d7500-0709-11e9-945a-4b206fd2a648.png)
And then the "ERROR 1698 (28000)" didn't occur.

---

Then, I find this error:
![image](https://user-images.githubusercontent.com/20783464/50385069-a40e2000-0709-11e9-8306-b64390da7dae.png)
Note that I don't know what should I type after "Enter password:", so I just type an [enter].
Perhaps there should be instructions to tell what to type after "Enter password:" in README.md.

---

Then, I find [this stackoverflow](https://stackoverflow.com/questions/4546778/how-can-i-import-a-database-with-mysql-from-terminal).
So, I type as below:
```
$ mysql -u b07902123
mysql> USE starwar;
ERROR 1049 (42000): Unknown database 'starwar'

mysql> SOURCE data/starwar.sql
(There are a lot of "ERROR 1046 (3D000): No database selected")
```

---

All I have done was just following the instructions in "Environment Setup", and there were a series of errors popping up. I am so confused that why there is few person asking questions about setup. I am using Ubuntu 18.04. Is there a more preferable operating system or environment to work on the homework?

Thanks a lot.

**Comment by ktpss95112** [comment]
@amjltc295

**Comment by amjltc295** [comment]
Did you try using sudo to do all the things?

**Comment by amjltc295** [comment]
I updated the instructions a bit in db3231efb49c771729c67034b6146e167e75c82b. Please tell me if you still have problems loading the database.

**Comment by ktpss95112** [comment]
Thanks for adding the instructions.
I use the following commands to pass environment setup:
```
$ sudo mysql -u root
mysql> CREATE DATABASE starwar;
mysql> exit;
$ cd SQL_Homework
$ sudo mysql -u root starwar < data/starwar.sql
$ sudo mysql -u root
mysql> USE starwar;
```
, for those who want to refer to.
