### ISSUE TITLE
 Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by archielu** [amjltc295/SQL_Homework#2]
When I load database from starwar.sql
"  Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) "
happens

**Comment by amjltc295** [comment]
Did you try to google it? https://stackoverflow.com/questions/11990708/error-cant-connect-to-local-mysql-server-through-socket-var-run-mysqld-mysq

**Comment by archielu** [comment]
I have tried every methods, but nothing work.

**Comment by amjltc295** [comment]
It is apparently a common issue as there are many google results. You have to provide error messages for each method you've tried then. Otherwise I cannot help.

**Comment by MrBear2000** [comment]
I had the same problem until I tried `sudo service mysql start`

**Comment by rajesh-manivannan** [comment]
> I had the same problem until I tried `sudo service mysql start`

This solution worked. Thank you so much!!
