### ISSUE TITLE
Screenshots in report

### ISSUE THREAD

**Issue by wesleysz** [amjltc295/SQL_Homework#22]
I found screenshots in my report.pdf in b07902019 was borken.
Can I hand in another report through email?

**Comment by amjltc295** [comment]
OK, but there may be some points deduction

**Comment by wesleysz** [comment]
謝謝助教！

________________________________
寄件者: Allen Chang <notifications@github.com>
寄件日期: 2019年1月2日 下午 12:35:11
收件者: amjltc295/SQL_Homework
副本: 江浩瑋; Author
主旨: Re: [amjltc295/SQL_Homework] Screenshots in report (#22)


OK, but there may be some points deduction

**Comment by amjltc295** [comment]
Please send to both TA's emails.
r07944011@ntu.edu.tw
r07944019@ntu.edu.tw
