### ISSUE TITLE
submit problem

### ISSUE THREAD

**Issue by Chaohsintsai** [amjltc295/SQL_Homework#24]
我把report.pdf傳成report.docx了 有辦法補救嗎？

**Comment by amjltc295** [comment]
Send us a mail with your correct version. There may be some points deduction

**Comment by Chaohsintsai** [comment]
i am B07902017
請問是傳給林與晨助教嗎？

**Comment by amjltc295** [comment]
Please send to both TA's emails.
r07944011@ntu.edu.tw
r07944019@ntu.edu.tw
