### ISSUE TITLE
Defination of time chunk

### ISSUE THREAD

**Issue by timothychen1999** [amjltc295/SQL_Homework#3]
Is the number indicates a point of a period of time?
aka. looks like
| 1 | 2 | 3 | 4 |...
or
|       |       |       |       |  
0      1      2     3      4   .......

**Comment by amjltc295** [comment]
See https://github.com/amjltc295/SQL_Homework#database . I don't get your question.

**Comment by timothychen1999** [comment]
![time](https://user-images.githubusercontent.com/45344933/50264023-c6771380-0453-11e9-8aef-b54a37fb6edd.png)
I mean does the time-chunk works like a. or b.

**Comment by amjltc295** [comment]
I see. It's like b.
