### ISSUE TITLE
QUESTION 4

### ISSUE THREAD

**Issue by aabb15768** [amjltc295/SQL_Homework#5]
about Q4 Find all characters that never visited any empire planets.
The answer about number of characters is 8, but shape of json say'it is 13'
error message on terminal is this"ERROR - Question 4 shape not match: yours: (8, 1) / ans: [13, 1]"
Am I wrong, or there is some bug in judge?

**Comment by amjltc295** [comment]
It is a bug. Fixed in 425d4ce326b324b8034076c3d18ca12c30fca80f
